export const ALLOWED_DIRECTIVES = {
	'base-uri': 'base-uri',
	'block-all-mixed-content': 'block-all-mixed-content',
	'child-src': 'child-src',
	'connect-src': 'connect-src',
	'default-src': 'default-src',
	'font-src': 'font-src',
	'form-action': 'form-action',
	'frame-ancestors': 'frame-ancestors',
	'frame-src': 'frame-src',
	'img-src': 'img-src',
	'manifest-src': 'manifest-src',
	'media-src': 'media-src',
	'object-src': 'object-src',
	'plugin-types': 'plugin-types',
	'prefetch-src': 'prefetch-src',
	'referrer': 'referrer',
	'report-uri': 'report-uri',
	'sandbox': 'sandbox',
	'script-src-attr': 'script-src-attr',
	'script-src-elem': 'script-src-elem',
	'script-src': 'script-src',
	'style-src-attr': 'style-src-attr',
	'style-src-elem': 'style-src-elem',
	'style-src': 'style-src',
	'upgrade-insecure-requests': 'upgrade-insecure-requests',
	'worker-src': 'worker-src',
};
